data:
  class_path: pl_modules.InferenceDataModule
  init_args:
    slice_dataset: data.CmrxReconInferenceSliceDataset
    #data_path: /gpfs/home/bingyx01/mridatasets/cmrxrecon2024/validationset/undersample
    data_path: /common/lidxxlab/cmrchallenge/data/CMR2024/ChallengeData/MultiCoil
    challenge: multicoil
    test_transform:
      class_path: data.CmrxReconDataTransform
      init_args:
        mask_func: null
        uniform_resolution: null
        use_seed: True
        mask_type: 'cartesian_or_radial'
        test_num_low_frequencies: 16
    num_adj_slices: 5
    batch_size: 1
    distributed_sampler: true 
    test_filter: 
      class_path: data.FuncFilterString
      init_args:
        filter_str: Mapping/ValidationSet/UnderSample_Task1/

# dataset specific settings
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 4
  num_nodes: 1
  logger: False
  callbacks:
    -
      class_path: __main__.CustomWriter
      init_args:
        #output_dir: _predict/cmr24-cardiac/test_plus
        output_dir: output_chushu/CMR2024
        write_interval: batch_and_epoch
model:
  class_path: pl_modules.PromptMrModule

ckpt_path: None 
