# ckpt_path: /common/lidxxlab/Yi/training_results_folder/multi_dataset_training_kloss/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/ophww12n/checkpoints/best-epochepoch=08-valvalidation_loss=0.0156.ckpt #slice 5
# ckpt_path: /common/lidxxlab/Yi/training_results_folder/multi_dataset_training_dataset_specific/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/dod22k1j/checkpoints/best-epochepoch=08-valvalidation_loss=0.0143.ckpt #slice 7
# ckpt_path: /common/lidxxlab/cmrchallenge/task3/PromptMR-plus-Task4_kloss/multi_dataset_training_kloss/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/4011nm3j/checkpoints/best-epochepoch=12-valvalidation_loss=0.0127.ckpt
# ckpt_path: /common/lidxxlab/cmrchallenge/task3/PromptMR-plus-Task4_kloss/multi_dataset_training_kloss/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/4011nm3j/checkpoints/best-epochepoch=10-valvalidation_loss=0.0129.ckpt
# ckpt_path: /common/lidxxlab/cmrchallenge/task3/PromptMR-plus-Task4_kloss/multi_dataset_training_3T_finetune2/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/bosarbui/checkpoints/best-epochepoch=01-valvalidation_loss=0.0128.ckpt
ckpt_path: /common/lidxxlab/cmrchallenge/task3/PromptMR-plus-Task4_kloss/multi_dataset_training_3T_finetune2/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/bosarbui/checkpoints/best-epochepoch=00-valvalidation_loss=0.0130.ckpt
# ckpt_path: /common/lidxxlab/cmrchallenge/task3/PromptMR-plus-Task4_kloss/multi_dataset_training_3T_finetune5/promptmr-plus/CMR2024_2025_dataset_specific/cmr2024_2025_phased/kuhlyn3f/checkpoints/best-epochepoch=00-valvalidation_loss=0.0138.ckpt

data:
  class_path: pl_modules.InferenceDataModule
  init_args:
    slice_dataset: data.CmrxReconInferenceSliceDataset
    # data_path: /common/lidxxlab/cmrchallenge/data/CMR2025/Validation/Task2/TaskR2/MultiCoil
    # data_path: /common/lidxxlab/cmrchallenge/data/CMR2025/Validation/TaskR1/MultiCoil
    data_path: /common/lidxxlab/cmrchallenge/data/CMR2025/Validation/Task3-S1/TaskS1/MultiCoil
    challenge: multicoil
    test_transform:
      class_path: data.CmrxReconDataTransform

      init_args:
        mask_func: null
        uniform_resolution: null
        use_seed: True
        mask_type: 'cartesian_or_radial'
        test_num_low_frequencies: 16
        uniform_resolution: null
        use_seed: true
        
        # test_num_low_frequencies: -1   # If mask_func is none, use this parameter
    num_adj_slices: 7 
    batch_size: 1
    num_workers: 1
    # pin_memory: true
    distributed_sampler: false
    test_filter: 
      class_path: data.FuncFilterString
      init_args:
        filter_str: null


# dataset specific settings
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: ddp
  devices: 1
  precision: 16 
  num_nodes: 1
  
  # Disable logger completely (no wandb)
  logger: false

  callbacks:
    - class_path: __main__.CustomWriter
      init_args:
        output_dir: /common/lidxxlab/cmrchallenge/task3/output/inference_results_baseline3Tfinetune_second_0epoch_7slice
        write_interval: batch_and_epoch
        

model:
  class_path: pl_modules.PromptMrModule
  init_args:
    # Model architecture 
    num_cascades: 16               # Number of cascade blocks
    num_adj_slices: 7              # Number of adjacent slices
    n_feat0: 48                    # Base feature channels
    
    # Feature dimensions
    feature_dim: [72, 96, 120]     # Feature dimensions for three levels
    prompt_dim: [24, 48, 72]       # Prompt dimensions for three levels
    
    # Sensitivity coil parameters
    sens_n_feat0: 24               # Base feature channels for sensitivity coil
    sens_feature_dim: [36, 48, 60] # Feature dimensions for sensitivity coil
    sens_prompt_dim: [12, 24, 36]  # Prompt dimensions for sensitivity coil
    
    # Prompt parameters
    len_prompt: [5, 5, 5]          # Number of prompt components for each level
    prompt_size: [64, 32, 16]      # Spatial size of prompt features
    
    # Network components
    n_enc_cab: [2, 3, 3]           # Number of encoder CABs
    n_dec_cab: [2, 2, 3]           # Number of decoder CABs
    n_skip_cab: [1, 1, 1]          # Number of skip connection CABs
    n_bottleneck_cab: 3            # Number of bottleneck CABs
    
    # Feature switches
    no_use_ca: false               # Whether not to use channel attention
    learnable_prompt: false        # Whether prompt parameters are learnable
    adaptive_input: true           # Whether to use adaptive input
    n_buffer: 4                    # Buffer size
    n_history: 15                  # Number of history features
    use_sens_adj: true             # Whether to use sensitivity coil adjacency processing

    # Other parameters
    use_checkpoint: false          # Whether to use gradient checkpointing
    compute_sens_per_coil: false   # Whether to compute sensitivity map per coil
    pretrain: false                # Whether to use pretraining
    pretrain_weights_path: null
    num_log_images: 16             # Number of images to log

# python main.py predict --config configs/inference/pmr-plus/cmr-task4-val-no-wandb.yaml
